spring.application.name=TaskManagerAPI
spring.datasource.url=jdbc:mysql://localhost:3306/TaskManager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=toor
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret.key=OUR_VERY_LONG_AND_SECURE_BASE64_ENCODED_SECRET_KEY_HERE_THAT_IS_AT_LEAST_256_BITS_LON